### ISSUE TITLE
the ban rate

### ISSUE THREAD

**Issue by SohaibArbiBakcha** [tokafew420/genshin-impact-tools#2]
i just found this tool want to ask about the ban rate from using yhis tool
is it modify anything in the file game or just scrap data
thanks for ur energy and the hard work

**Comment by SohaibArbiBakcha** [comment]
> 

sorry for i just read the code and i found that is just a web page 
sorry for bothring its my bad

**Comment by tokafew420** [comment]
Yes all of this data is scraped from the wiki.
